- name: install nginx
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: true
